2023-05-10 12:58:20,879 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 12:58:20,882 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 12:58:44,753 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 12:58:44,755 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 13:13:11,492 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {'username': 'admin', 'psd': 'Feefifofum'}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 13:13:11,494 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {'username': 'admin', 'psd': 'Feefifofum'}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 13:14:31,557 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 13:14:31,559 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 13:14:32,145 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {'0x[]': 'Graber'}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 13:14:32,148 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {'0x[]': 'Graber'}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 13:14:54,972 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 13:14:54,974 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 13:14:55,374 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {'0x[]': 'androxgh0st'}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
