2023-05-08 18:04:35,211 ERROR frappe New Exception collected with id: 2023-05-08 18:04:35.121938-127.0.0.1-43e
Site: classiccookie.local
Form Dict: {'cmd': 'frappe.www.login.send_login_link', 'email': 'johnnycpack@gmail.com'}
2023-05-08 20:14:03,821 ERROR frappe New Exception collected with id: 2023-05-08 20:14:03.819934-127.0.0.1-fda
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:05,025 ERROR frappe New Exception collected with id: 2023-05-08 20:19:05.023886-127.0.0.1-747
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:08,187 ERROR frappe New Exception collected with id: 2023-05-08 20:19:08.186106-127.0.0.1-de8
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:10,853 ERROR frappe New Exception collected with id: 2023-05-08 20:19:10.851781-127.0.0.1-fc9
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:13,343 ERROR frappe New Exception collected with id: 2023-05-08 20:19:13.342264-127.0.0.1-2f6
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:28,244 ERROR frappe New Exception collected with id: 2023-05-08 20:19:28.242698-127.0.0.1-761
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:19:30,454 ERROR frappe New Exception collected with id: 2023-05-08 20:19:30.452886-127.0.0.1-5a4
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:47,026 ERROR frappe New Exception collected with id: 2023-05-08 20:23:46.787405-127.0.0.1-ae5
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:47,383 ERROR frappe New Exception collected with id: 2023-05-08 20:23:47.382045-127.0.0.1-0b7
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:49,627 ERROR frappe New Exception collected with id: 2023-05-08 20:23:49.626831-127.0.0.1-a6b
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:49,900 ERROR frappe New Exception collected with id: 2023-05-08 20:23:49.899831-127.0.0.1-35c
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:55,147 ERROR frappe New Exception collected with id: 2023-05-08 20:23:55.146075-127.0.0.1-356
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:55,423 ERROR frappe New Exception collected with id: 2023-05-08 20:23:55.422515-127.0.0.1-03e
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:57,517 ERROR frappe New Exception collected with id: 2023-05-08 20:23:57.516572-127.0.0.1-162
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:23:57,838 ERROR frappe New Exception collected with id: 2023-05-08 20:23:57.837081-127.0.0.1-a50
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:00,432 ERROR frappe New Exception collected with id: 2023-05-08 20:24:00.430280-127.0.0.1-087
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:00,637 ERROR frappe New Exception collected with id: 2023-05-08 20:24:00.636062-127.0.0.1-170
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:00,921 ERROR frappe New Exception collected with id: 2023-05-08 20:24:00.920262-127.0.0.1-337
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:11,424 ERROR frappe New Exception collected with id: 2023-05-08 20:24:11.423652-127.0.0.1-4b7
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:11,699 ERROR frappe New Exception collected with id: 2023-05-08 20:24:11.698349-127.0.0.1-323
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:30,449 ERROR frappe New Exception collected with id: 2023-05-08 20:24:30.448809-127.0.0.1-0ee
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:30,709 ERROR frappe New Exception collected with id: 2023-05-08 20:24:30.708564-127.0.0.1-0b6
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:32,910 ERROR frappe New Exception collected with id: 2023-05-08 20:24:32.909751-127.0.0.1-96b
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:33,187 ERROR frappe New Exception collected with id: 2023-05-08 20:24:33.186460-127.0.0.1-344
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:59,507 ERROR frappe New Exception collected with id: 2023-05-08 20:24:59.431304-127.0.0.1-1c8
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:24:59,809 ERROR frappe New Exception collected with id: 2023-05-08 20:24:59.808209-127.0.0.1-f55
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:25:02,052 ERROR frappe New Exception collected with id: 2023-05-08 20:25:02.049791-127.0.0.1-5b8
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:25:02,426 ERROR frappe New Exception collected with id: 2023-05-08 20:25:02.422422-127.0.0.1-87b
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:25:03,289 ERROR frappe New Exception collected with id: 2023-05-08 20:25:03.288821-127.0.0.1-a97
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:25:03,595 ERROR frappe New Exception collected with id: 2023-05-08 20:25:03.594124-127.0.0.1-124
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:34,484 ERROR frappe New Exception collected with id: 2023-05-08 20:27:34.192601-127.0.0.1-d10
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:36,141 ERROR frappe New Exception collected with id: 2023-05-08 20:27:36.140645-127.0.0.1-a09
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:36,506 ERROR frappe New Exception collected with id: 2023-05-08 20:27:36.504874-127.0.0.1-cf0
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:40,792 ERROR frappe New Exception collected with id: 2023-05-08 20:27:40.791617-127.0.0.1-aec
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:41,073 ERROR frappe New Exception collected with id: 2023-05-08 20:27:41.070699-127.0.0.1-f21
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:43,824 ERROR frappe New Exception collected with id: 2023-05-08 20:27:43.822960-127.0.0.1-654
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:27:44,104 ERROR frappe New Exception collected with id: 2023-05-08 20:27:44.102966-127.0.0.1-5d6
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:21,827 ERROR frappe New Exception collected with id: 2023-05-08 20:29:21.663072-127.0.0.1-f6a
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:22,380 ERROR frappe New Exception collected with id: 2023-05-08 20:29:22.362570-127.0.0.1-17e
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:22,566 ERROR frappe New Exception collected with id: 2023-05-08 20:29:22.561625-127.0.0.1-343
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:22,638 ERROR frappe New Exception collected with id: 2023-05-08 20:29:22.637680-127.0.0.1-3ea
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:25,622 ERROR frappe New Exception collected with id: 2023-05-08 20:29:25.619392-127.0.0.1-74a
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:29:25,899 ERROR frappe New Exception collected with id: 2023-05-08 20:29:25.898780-127.0.0.1-c9e
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:31:59,705 ERROR frappe New Exception collected with id: 2023-05-08 20:31:59.537155-127.0.0.1-419
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:32:00,046 ERROR frappe New Exception collected with id: 2023-05-08 20:32:00.044517-127.0.0.1-65a
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:19,621 ERROR frappe New Exception collected with id: 2023-05-08 20:33:19.544229-127.0.0.1-fab
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:19,905 ERROR frappe New Exception collected with id: 2023-05-08 20:33:19.904037-127.0.0.1-297
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:23,780 ERROR frappe New Exception collected with id: 2023-05-08 20:33:23.779547-127.0.0.1-b35
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:24,071 ERROR frappe New Exception collected with id: 2023-05-08 20:33:24.070601-127.0.0.1-a56
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:26,312 ERROR frappe New Exception collected with id: 2023-05-08 20:33:26.311353-127.0.0.1-216
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:26,609 ERROR frappe New Exception collected with id: 2023-05-08 20:33:26.608405-127.0.0.1-95d
Site: classiccookie.local
Form Dict: {}
2023-05-08 20:33:39,232 ERROR frappe New Exception collected with id: 2023-05-08 20:33:39.231926-127.0.0.1-525
Site: classiccookie.local
Form Dict: {}
2023-05-09 18:29:59,637 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-09 18:29:59,641 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-09 18:30:02,038 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-09 18:30:02,041 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-09 18:30:02,883 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-09 18:30:02,886 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-09 18:30:03,899 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-09 18:30:03,902 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-09 18:30:11,369 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-09 18:30:11,372 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 291, in resume
    validate_ip_address(self.user)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 410, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1129, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'active_users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
2023-05-10 12:58:20,661 ERROR frappe Could not take error snapshot: characters_written
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 48, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/error.py", line 141, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2023-05-10 12:58:20,671 ERROR frappe Failed to run after request hook
Site: classiccookie.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 42, in application
    init_request(request)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 131, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 36, in __init__
    self.set_session()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 220, in __init__
    self.resume()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 286, in resume
    data = self.get_session_record()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 303, in get_session_record
    r = self.get_session_data()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 317, in get_session_data
    data = self.get_session_data_from_cache()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/sessions.py", line 330, in get_session_data_from_cache
    frappe.utils.now(), session_data.get("last_updated")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 308, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 329, in get_system_timezone
    return frappe.cache().get_value("time_zone", _get_system_timezone)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 96, in get_value
    val = generator()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/data.py", line 322, in _get_system_timezone
    return frappe.db.get_system_setting("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/database/database.py", line 1153, in get_system_setting
    return frappe.get_system_settings(key)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 2280, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1078, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1163, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 47, in get_controller
    return import_controller(doctype)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/model/base_document.py", line 69, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 36, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 71, in application
    response = handle_exception(e)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 326, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1335, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1352, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1444, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1306, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'runner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 85, in application
    run_after_request_hooks(request, response)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/app.py", line 102, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1475, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/ubuntu/cc-bench/apps/frappe/frappe/__init__.py", line 1450, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe
